services:
  db:
    image: postgres:15.1-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: magic

  cafe_app:
    build: .
    image: cafe_app
    container_name: cafe_app
    command: poetry run start
    ports:
      - 8000:8000
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  tests:
    build: ./tests
    image: tests
    container_name: tests
    depends_on:
      - cafe_app
    network_mode: "host"
