services:
  db:
    image: postgres:15.1-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: magic

  cafe_app:
    build: ./cafe_api
    image: cafe_app
    command: poetry run start
    ports:
      - 8000:5000
    depends_on:
      - db
